name: whisper-api-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - ffmpeg
  - pip
  - pip:
      - fastapi==0.98.0
      - uvicorn==0.22.0
      - numpy==1.24.3
      - "git+https://github.com/openai/whisper.git"
      - torch==2.0.1
      - torchaudio==2.0.2
      - python-multipart=0.0.20
      - ffmpeg-python==0.2.0
