
services:
  # ------------------------------------------------
  # Chroma Postgres
  # ------------------------------------------------
  cal_chromadb_postgres:
    image: postgres:17.2
    container_name: cal_chromadb_postgres
    environment:
      POSTGRES_USER: "${CHROMA_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${CHROMA_POSTGRES_PASSWORD}"
      POSTGRES_DB: "${CHROMA_POSTGRES_DB}"
    ports:
      - "${CHROMA_POSTGRES_PORT:-5432}:5432"
    volumes:
      - cal_chromadb_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # ------------------------------------------------
  # Chroma DB
  # ------------------------------------------------
  cal_chromadb:
    image: chromadb/chroma:latest
    container_name: cal_chromadb
    environment:
      CHROMA_DB_IMPL: "postgresql"
      CHROMA_DB_HOST: "cal_chromadb_postgres"
      CHROMA_DB_PORT: "5432"
      CHROMA_DB_USER: "${CHROMA_POSTGRES_USER}"
      CHROMA_DB_PASSWORD: "${CHROMA_POSTGRES_PASSWORD}"
      CHROMA_DB_DATABASE: "${CHROMA_POSTGRES_DB}"
      CHROMA_DB_MIGRATE_ON_START: "true"
      CHROMA_SERVER_AUTHN_PROVIDER: "chromadb.auth.basic_authn.BasicAuthenticationServerProvider"
      CHROMA_SERVER_AUTHN_CREDENTIALS: "${CHROMA_SERVER_AUTHN_CREDENTIALS}"
    depends_on:
      - cal_chromadb_postgres
    ports:
      - "8000:8000"
    restart: unless-stopped

  # ------------------------------------------------
  # New Postgres for Non-Chroma App Data
  # ------------------------------------------------
  cal_app_postgres:
    image: postgres:17.2
    container_name: cal_app_postgres
    environment:
      POSTGRES_USER: "${APP_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${APP_POSTGRES_PASSWORD}"
      POSTGRES_DB: "${APP_POSTGRES_DB}"
    ports:
      - "${APP_POSTGRES_PORT:-5433}:5432"
    volumes:
      - cal_app_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped


volumes:
  cal_chromadb_postgres_data:
  cal_app_postgres_data:
