export const VERBS = ['schedule', 'book', 'add', 'create', 'make', 'set up'];

export const TITLES = ['doctor', 'mister', 'miss', 'misses', 'professor', 'engineer'];

export const STARTERS = [
  'Hey can you',
  'Can you',
  'Can you please',
  'Can you help me',
  'Please',
  'Please help me',
  'Please can you',
  'I need you to',
];

export const TIMES = [
  'tomorrow',
  'today',
  'next week',
  'next month',
  'this week',
  'this month',
  'this year',
  'in the next hour',
  'in the next 30 minutes',
];

export const ENTITIES = ['appointment', 'meeting', 'reminder', 'event', 'schedule', 'calendar', 'task', 'to-do', 'reminder', 'alarm', 'notification'];

export const LOCATIONS = [
  'at the office',
  'at home',
  'at the park',
  'at the store',
  "at the doctor's office",
  'at the dentist',
  'at the hospital',
  'at the bank',
  'at the post office',
  'at the library',
  'at the gym',
  'at the school',
  'at the university',
  'at the college',
  'at the airport',
  'at the train station',
  'at the bus station',
  'at the beach',
  'at the pool',
  'at the lake',
  'at the river',
  'at the mountains',
  'at the forest',
  'at the park',
  'at the zoo',
  'at the aquarium',
  'at the museum',
  'at the theater',
  'at the cinema',
  'at the restaurant',
  'at the cafe',
  'at the bar',
  'at the pub',
  'at the club',
  'at the party',
  'at the wedding',
  'at the funeral',
  'at the birthday party',
  'at the baby shower',
  'at the bridal shower',
  'at the graduation',
  'at the ceremony',
  'at the concert',
  'at the festival',
  'at the parade',
  'at the protest',
  'at the rally',
  'at the conference',
  'at the convention',
  'at the expo',
  'at the fair',
  'at the market',
  'at the garage sale',
  'at the yard sale',
  'at the flea market',
  'at the swap meet',
  'at the auction',
  'at the estate sale',
  'at the thrift store',
  'at the charity shop',
  'at the pawn shop',
  'at the bank',
  'at the post office',
  'at the library',
  'at the gym',
  'at the school',
  'at the university',
  'at the college',
  'at the airport',
  'at the train station',
  'at the bus station',
  'at the beach',
  'at the pool',
  'at the lake',
  'at the river',
  'at the mountains',
  'at the forest',
  'at the park',
  'at the zoo',
];
